### ISSUE TITLE
Alias detection does not respect "AS"

### ISSUE THREAD

**Issue by mrblur** [waldo2188/DatatableBundle#10]
Took me an hour to find out, why simple field
```php
$x->setFields([
 'Entities' => 'SIZE(x.entities)'
]);
```

Throws an error.
```
Notice: Undefined index: SIZE(x_entities)
```

According to docs, it needs to be aliased, so I tried
```php
$x->setFields([
 'Entities' => 'SIZE(x.entities) AS entities'
]); 
```
to receive:
```
Notice: Undefined index: SIZE(x_entities) AS entities
```

Had to read the code to find out that this is not DQL, it **is case-sensitive** and to work - aliasing keyword has to be written lowercase:
```php
$x->setFields([
 'Entities' => 'SIZE(x.entities) as entities'
]); 
```

I believe that aliasing should be respected case-insensitive. Or, at least, there should be a bold statement in the docs :wink:

**Comment by waldo2188** [comment]
Yep, you're right.
I will change the doc to specify that `as` is case sensitive.
