### ISSUE TITLE
More information about how to add actions on each row

### ISSUE THREAD

**Issue by wysow** [waldo2188/DatatableBundle#11]
Hello @waldo2188 can you give more information about how to add some actions in a ceil for each row?

Using the solution in the `README` is not really working for me, maybe I'm missing something...

Using version `4.0.2` with dataTable version `1.10.12` from their CDN.

**Comment by wysow** [comment]
Hum... just made it like this:

```php
$this->get('datatable')
            ->setEntity('IxoilPurchaserBundle:OrderContext', 'oc')
            ->setFields([
                ...
                $this->get('translator')->trans('grid.column.actions', [], 'grids') => 'oc.id',
                '_identifier_'                                                                                      => 'oc.id',
            ])
```

Does it sounds right for you?

**Comment by waldo2188** [comment]
Hy!
Your code looks good.
I've made this (https://github.com/waldo2188/datatable-sandbox) for playing with the datatable.
Maybe it will help you.

**Comment by wysow** [comment]
Thanks, seems working as expected, closing this so...
