### ISSUE TITLE
Display a Datetime Value

### ISSUE THREAD

**Issue by janie24** [waldo2188/DatatableBundle#19]
I have a problem with displaying a datetime Object. I have a field which is declared as "datetime" in my entity. When I put this field in the "setFields" Value ("StartDtTm" => 'csm.startdttm') I get this in my table:
[object Object]
When I look at the json return it is an array:
{"date":"2015-12-05 02:01:54","timezone_type":3,"timezone":"Europe\/Berlin"}

But I have no idea how to get the "date" value from this array. 'csm.startdttm.date' is not working.
Please help me

**Comment by osmanyilmazco** [comment]
Hmm, I do this thing.. 
For example created_at column.

`$fields = [
'#' => 'c.id', 
"Name" => 'c.name',
"Date" => 'c.id',  
"_identifier_" => 'c.id'
];`

`$renders = [
2 => [ 'view' => 'backend/product/datatable/created-at.html.twig'],
3 => [ 'view' => 'backend/product/datatable/options.html.twig']
];`

**Render View Path: backend/product/datatable/created-at.html.twig**
`{{ dt_obj.createdAt|date('d.m.Y H:i') }}`

I hope it works. (My English is not very good. Sorry :))

**Comment by janie24** [comment]
Thank you so much, it works :)
