### ISSUE TITLE
Problem sort column with method "setMultiple()"

### ISSUE THREAD

**Issue by bunsky** [waldo2188/DatatableBundle#2]
When using the method setMutiple() , column sorting do not work properly .

The sorting is done on the next column.

Is there a solution ?

Thank you

**Comment by waldo2188** [comment]
Hi,
I can not reproduce this behavior.
Can you try this sandbox app https://github.com/waldo2188/datatable-sandbox ?

I've made a page to test the multiple selection. Try if you have the same behavior than in your application.
