### ISSUE TITLE
Datetime field

### ISSUE THREAD

**Issue by alejgarciarodriguez** [waldo2188/DatatableBundle#26]
It is possible to set a datetime in column with a specific format? Something like:

```
$this->get('datatable')
            ->setEntity("AppBundle:EmailEntity, "e")
            ->setFields(
                array(
                    'Created On' => 'date_format(e.createdOn, "%M")',
                    "_identifier_" => 'e.id',
                )
            )
```

**Comment by osmanyilmazco** [comment]
Hi, perhaps may be helpful. #19

**Comment by gbtux** [comment]
yes you can with renderer / closure (https://github.com/waldo2188/DatatableBundle#php-closures)

My code : 
`foreach ($data as $key => $value) {
                        if ($key == 0) { //date creation
                            $data[$key] = $value->format('d-m-Y');
                        }`
