### ISSUE TITLE
Twig Problem

### ISSUE THREAD

**Issue by Xeyos88** [waldo2188/DatatableBundle#3]
Hi,
if i use this format

``` twig
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/r/dt/dt-1.10.9/datatables.min.css"/>
<script type="text/javascript" src="//code.jquery.com/jquery-2.1.4.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/r/dt/dt-1.10.9/datatables.min.js"></script>

{{ datatable({
        'js' : {
            'ajax' : path('route_for_your_datatable_action')
        }
    })
}}
{{ datatable({
        'js' : {
            'ajax' : path('route_for_your_datatable_action')
        }
    })
}}
```

I don't see any

If i use this

``` twig
% block body %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/r/dt/dt-1.10.9/datatables.min.css"/>
    {{ datatable_html({
            'id' : 'dta-offres'
        })
    }}

{% endblock %}

{% block javascripts %}
<script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.10.2.min.js"></script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.9/js/jquery.dataTables.js"></script>
{{ datatable_js({
        'id' : 'dta-offres',
        'js' : {
            'dom': '<"clearfix"lf>rtip',
            'ajax': path('route_for_your_datatable_action'),
        }
    })
}}
{% endblock javascripts %}
```

I see the results but i have the reinitialise datatable error
DataTables warning: table id=dta-offres - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

Second question
how can I have a rendering as in your example image?

**Comment by Xeyos88** [comment]
Solved this part
DataTables warning: table id=dta-offres - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3
but search filter doesn't work

if i add ->setSearch(true)
i have this error
DataTables warning: table id=dta-offres - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by waldo2188** [comment]
Hi,
Which version of Datatable Bundle are you using ?
Can you check if the `route_for_your_datatable_action` return a valid Json ?
