### ISSUE TITLE
Problem with js defaults for number of entries

### ISSUE THREAD

**Issue by softimpulse** [waldo2188/DatatableBundle#4]
At least in DatatableBundle version 4.0.1 the "show number of entries combo" is generated wrong in the final html, it looks like:
```
<select class="">
<option value="[">[</option>
<option value="[">[</option>
<option value="1">1</option>
<option value="0">0</option>
<option value=",">,</option>
<option value=" "> </option>
. . . .
```
Could be fixed by changing the line
```
"lengthMenu" => '[[10, 25, 50, -1], [10, 25, 50, "All"]]',
```
by
```
"lengthMenu" => array(array(10, 25, 50, -1), array(10, 25, 50, "All")),
```
in `vendor/waldo/datatable-bundle/DependencyInjection/WaldoDatatableExtension.php`

I've made a mostly default install, jquery is 1.10.2, DataTables.min 1.10.9.

Thanks for the bundle - at least my first steps were rather easy!

Matthias

**Comment by waldo2188** [comment]
Thanks to have find this bug. I hadn't seen it...
