### ISSUE TITLE
Symfnoy3 - compatible ?

### ISSUE THREAD

**Issue by ychoucha** [waldo2188/DatatableBundle#5]
hello, can we using bundle with symfony3 :+1: 
because after installing bundle  i have this error  : 

```
Unable to parse file "/var/www/html/Symfony/vendor/waldo/datatable-bundle/DependencyInjection/../Resources/config/services.xml".
```

how fix it please ?

**Comment by flopp26** [comment]
Same error here, always with symfony3! also need a fix ;-)

**Comment by waldo2188** [comment]
Which version of the bundle did you use ?

I've just try with a fresh Symfony 3 install, and it raise no error.

**Comment by flopp26** [comment]
Hi, thanks for your answer.

My first try I use : composer require waldo/datatable-bundle, but I get error (see above)
I have change my composer.json with this :
```
    "require": {
        .......................
        "symfony/symfony": "3.1.*",
        "waldo/datatable-bundle": "~3.0"
    `},
```
but It stil not works. I use symfony 3.1.2
ERROR 1866 attribute 'scope' is not allowed

**Comment by waldo2188** [comment]
Ok, version 3 of datatablebundle is an old version.
Try with the 4.0.2, it will work better.

**Comment by flopp26** [comment]
Yes better with 4.02 :-) no errors, thanks
